const config = {
  url: 'https://api.site-news.tk',
  login: 'https://api.site-news.tk/signin',
  signup: 'https://api.site-news.tk/signup',
  logout: 'https://api.site-news.tk/logout',
  getUser: 'https://api.site-news.tk/users/me',
  articles: 'https://api.site-news.tk/articles',
  git: 'https://github.com/lucky091285/news-explorer-frontend.git',
  maxGitCommits: 15,
  month: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа',
    'сентября', 'октября', 'ноября', 'декабря'],
  newsFeed: 'https://newsapi.org/v2/everything?sortBy=popularity&apiKey=32d93de8aad245a2986cdb37bec3d666&language=ru&pageSize=100',
  showMore: { node: '#show-more', hide: 'results__button_hide' },
  showStep: 3,
  cardSample: '#card-sample',
  card: {
    node: '.card',
    img: '.card__pic',
    date: '.card__date',
    title: '.card__title',
    text: '.card__text',
    src: '.card__src',
    warning: '.card__auth',
    keyword: '.card__keyword',
    icon: {
      node: '.card__icon',
      logged: 'card__icon_logged',
      marked: 'card__icon_marked',
      bin: 'card__icon_delete',
    },
  },
  resultsField: '.results__news',
  newsForm: 'news-finder',
  newsFormSearchField: 'search',
  preloader: { node: '#preloader-searching', hide: 'preloader__message_hide' },
  notFound: { node: '#preloader-not-found', hide: 'preloader__message_hide' },
  serverError: { node: '#preloader-server-error', hide: 'preloader__message_hide' },
  resultsSection: { node: '.results', hide: 'results_hide' },
  collectionContainer: '.storage',
  articlesSum: '.articles-sum',
  articlesHeader: '.saved-papers__title',
  words: {
    first: '.first-word',
    second: '.second-word',
    more: '.and-more',
    tail: '.word-tail',
  },
};

export default config;
