const config = {
  url: 'https://api.site-news.tk',
  signInUrl: 'https://api.site-news.tk/signin',
  signUpUrl: 'https://api.site-news.tk/signup',
  logOutUrl: 'https://api.site-news.tk/logout',
  getUser: 'https://api.site-news.tk/users/me',
  articles: 'https://api.site-news.tk/articles',
  git: 'https://api.github.com/repos/lucky091285/news-explorer-frontend/commits',
  maxGitCommits: 15,
  month: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа',
    'сентября', 'октября', 'ноября', 'декабря'],
  sevenDays: (7 * 24 * 3600 * 1000),
  newsFeed: 'https://newsapi.org/v2/everything?sortBy=popularity&apiKey=32d93de8aad245a2986cdb37bec3d666&language=ru&pageSize=100',
  results: {
    viewStep: 3,
    showMoreButton: { node: '#show-more', hide: 'results__button_hide' },
    resultsField: '.results__news',
    newsForm: '.search__form',
    newsFormSearchField: '.search__form-input',
    newsFormButton: '#search-the-news',
    preloader: { node: '#preloader-searching', hide: 'preloader__message_hide' },
    foundError: { node: '#preloader-not-found', hide: 'preloader__message_hide' },
    serverError: { node: '#preloader-server-error', hide: 'preloader__message_hide' },
    resultsSection: { node: '.results', hide: 'results_hide' },
  },
  cardSample: '#card-sample',
  card: {
    node: '.card',
    img: '.card__pic',
    date: '.card__date',
    title: '.card__title',
    text: '.card__text',
    src: '.card__src',
    auth: '.card__auth',
    keyword: '.card__keyword',
    icon: {
      node: '.card__icon',
      logged: 'card__icon_logged',
      marked: 'card__icon_marked',
      basket: 'card__icon_basket',
    },
  },
  collection: {
    collectionContainer: '.storage',
    articlesSum: '.articles-sum',
    articlesHeader: '.saved-papers__title',
    words: {
      first: '.first-word',
      second: '.second-word',
      more: '.and-more',
      tail: '.word-tail',
    },
  },
  slider: {
    node: '.slider',
    commitDate: '.slider__commit-date',
    commitImage: '.slider__commit-image',
    commitName: '.slider__commit-name',
    commitEmail: '.slider__commit-email',
    commitText: '.slider__commit-text',
    template: '#commit-sample',
    swiperWrap: '.swiper-wrapper',
  },
};

export default config;
